image: docker:latest

variables:
  REGISTRY: hb.k8sbridge.com
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $REGISTRY/demo/spring-boot:$CI_COMMIT_SHORT_SHA
  CONTAINER_RELEASE_IMAGE: $REGISTRY/demo/spring-boot:latest
  KUBECTL_ARGUMENT: --token=$KUBERNETES_TOKEN --server=$KUBERNETES_SERVER --insecure-skip-tls-verify=true
  HARBOR_PASSWORD: $HARBOR_PW

services:
  - name: docker:latest

stages:
  - build
  - test
  - release
  - deploy

build:jar:
  tags:
    - docker
  image:
    name: hb.k8sbridge.com/demo/maven:base
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/
    untracked: true
    expire_in: 1 hour

sonarqube-check:
  tags:
    - docker
  dependencies:
    - build:jar
  image:
    name: sonarsource/sonar-scanner-cli
    entrypoint: [""]
  stage: test
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  before_script:
    - apk add jq curl
  script:
    - sonar-scanner -Dsonar.projectKey=test -Dsonar.sources=src -Dsonar.host.url=${SONAR_SERVER} -Dsonar.login=${SONAR_TOKEN} -Dsonar.qualitygate.wait=true -Dsonar.java.binaries=target
    - export url=$(cat .scannerwork/report-task.txt | grep ceTaskUrl | cut -c11- )
    - sleep 15s
    - curl -s -k -u "$SONAR_TOKEN":"" $url -o analysis.txt
    - export status=$(cat analysis.txt | jq -r '.task.status')
    - export analysisId=$(cat analysis.txt | jq -r '.task.analysisId')
    - |
      if [ "$status" != "SUCCESS" ];then
        echo -e "\e[91mSONAR ANALYSIS FAILED\e[0m"
        exit 1
      fi
    - curl -s -k -u "${SONAR_TOKEN}":"" "$SONAR_SERVER/api/qualitygates/project_status?analysisId=$analysisId" -o sonarqube-result.txt
    - export result=$(cat sonarqube-result.txt | jq -r '.projectStatus.status')
    - |
      if [ "$result" == "ERROR" ]; then
        echo -e "91mSONAR RESULTS FAILED"
        cat sonarqube-result.txt | jq -r '.projectStatus.conditions'
        exit 1
      fi
    - echo -e "SONAR RESULTS SUCCESSFUL"
    - cat sonarqube-result.txt | jq -r '.projectStatus.conditions'
  artifacts:
    paths:
      - sonarqube-result.txt
    expire_in: 1 hour
