apiVersion: v1
kind: Service
metadata:
  name: spring-boot-__CI_COMMIT_REF_SLUG__
  namespace: default
  labels:
    app: spring-boot-__CI_COMMIT_REF_SLUG__
spec:
  type: LoadBalancer
  ports:
    - name: http-metrics
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-__CI_COMMIT_REF_SLUG__
